INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('Mi', NULL, 'Mittelzehrer');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiG', 'Mi', 'Gemüse');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGAMARANTH ', 'MiG', 'Amaranth ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGBETE ', 'MiG', 'Bete ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGCHILI ', 'MiG', 'Chili ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGFENCHEL ', 'MiG', 'Fenchel ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGKOHLRABI ', 'MiG', 'Kohlrabi ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGLAUCHZWIEBEL ', 'MiG', 'Lauchzwiebel ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGMANGOLD ', 'MiG', 'Mangold ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGMÖHRE ', 'MiG', 'Möhre ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGPAPRIKA ', 'MiG', 'Paprika ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGPASTINAKE ', 'MiG', 'Pastinake ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGPFEFFERONI ', 'MiG', 'Pfefferoni ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGRETTICH ', 'MiG', 'Rettich ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGSALAT ', 'MiG', 'Salat ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGSCHWARZWURZEL ', 'MiG', 'Schwarzwurzel ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiGSPINAT ', 'MiG', 'Spinat ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiK', 'Mi', 'Kräuter');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiKPETERSILIE ', 'MiK', 'Petersilie ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiP', 'Mi', 'Pflanzgut');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiPKNOBLAUCH ', 'MiP', 'Knoblauch ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiPKNOLLIGER ', 'MiP', 'Knolliger ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiPSCHALOTTE ', 'MiP', 'Schalotte ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('MiPZWIEBEL ', 'MiP', 'Zwiebel ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('Sc', NULL, 'Schwachzehrer');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScG', 'Sc', 'Gemüse');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScGBOHNE ', 'ScG', 'Bohne ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScGERBSE ', 'ScG', 'Erbse ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScGMAIRÜBE ', 'ScG', 'Mairübe ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScGRADIESCHEN ', 'ScG', 'Radieschen ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScGSALAT ', 'ScG', 'Salat ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScK', 'Sc', 'Kräuter');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKBASILIKUM ', 'ScK', 'Basilikum ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKBRUNNENKRESSE', 'ScK', 'Brunnenkresse');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKDILL ', 'ScK', 'Dill ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKKNOBLAUCHSRAUKE', 'ScK', 'Knoblauchsrauke');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKKORIANDER', 'ScK', 'Koriander');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScKLAUCH-HELLERKRAUT', 'ScK', 'Lauch-Hellerkraut');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScP', 'Sc', 'Pflanzgut');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('ScPTOPINAMBUR ', 'ScP', 'Topinambur ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('St', NULL, 'Starkzehrer');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StG', 'St', 'Gemüse');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGANDENBEERE ', 'StG', 'Andenbeere ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGAUBERGINE ', 'StG', 'Aubergine ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGBLUMENKOHL ', 'StG', 'Blumenkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGBROKKOLI ', 'StG', 'Brokkoli ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGCHINAKOHL ', 'StG', 'Chinakohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGGRÜNKOHL ', 'StG', 'Grünkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGGURKE ', 'StG', 'Gurke ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGKÜRBIS ', 'StG', 'Kürbis ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGLAUCH ', 'StG', 'Lauch ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGMELONE ', 'StG', 'Melone ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGPALMKOHL ', 'StG', 'Palmkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGROSENKOHL ', 'StG', 'Rosenkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGROTKOHL ', 'StG', 'Rotkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGSELLERIE ', 'StG', 'Sellerie ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGTOMATE ', 'StG', 'Tomate ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGWEIßKOHL ', 'StG', 'Weißkohl ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGWIRSING ', 'StG', 'Wirsing ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGZUCCHINI ', 'StG', 'Zucchini ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StGZUCKERMAIS ', 'StG', 'Zuckermais ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StP', 'St', 'Pflanzgut');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StPKARTOFFEL ', 'StP', 'Kartoffel ');
INSERT INTO willibald_shop_p2.Kategorie (KatID, OberKatID, Name) VALUES	 ('StPSÜßKARTOFFEL ', 'StP', 'Süßkartoffel ');