
truncate table DIMENSIONAL_WILLIBALD.bestellung;

INSERT INTO DIMENSIONAL_WILLIBALD.DIM_BESTELLUNG
( _DK_BESTELLUNG
, BESTELLUNGID
, BESTELLDATUM
, WUNSCHDATUM
, RABATT
, RABATTBETRAG
, MITGLIEDSBONUS
, GESAMTBETRAG
, UMSATZSTEUER)
select 
 BESTELLUNGID
, BESTELLUNGID
, BESTELLDATUM
, WUNSCHDATUM
, RABATT
, RABATTBETRAG
, MITGLIEDSBONUS
, GESAMTBETRAG
, UMSATZSTEUER
from  willibald_xt.bestellung;

/* 
 * select * from 	 DIMENSIONAL_WILLIBALD.dim_bestellung
 */
