
truncate table DIMENSIONAL_WILLIBALD.DIM_BESTELLUNG;

INSERT INTO DIMENSIONAL_WILLIBALD.DIM_BESTELLUNG
( _DK_BESTELLUNG
, BESTELLUNGID
, BESTELLDATUM
, WUNSCHDATUM
, RABATT
, RABATTBETRAG
, MITGLIEDSBONUS
, GESAMTBETRAG
, UMSATZSTEUER)
select 
 BESTELLUNGID
, BESTELLUNGID
, BESTELLDATUM
, WUNSCHDATUM
, RABATT
, RABATTBETRAG
, MITGLIEDSBONUS
, GESAMTBETRAG
, UMSATZSTEUER
from  willibald_xt.bestellung
	where bestellungid in (Select bestellungid from willibald_xt.data_sample_bestellung);


/* 
 * select * from 	 DIMENSIONAL_WILLIBALD.dim_bestellung
 */
